#!/bin/bash

## This utility creates the followinf variables:
#  $wpdbinfoapi_databasename
#  $wpdbinfoapi_databaseuser
#  $wpdbinfoapi_databasepass
#  $wpdbinfoapi_databasehost


# Utility version
wpdbinfoapi_version=4

do_wpdbingoapi() {

    # Checks if the first parameter was provided
    if [ -z $1 ]; then
        echo You need provides the first paramater to be the wordpress base directory.
        return
    fi

    # Checks if the parameter provides corresponds to a directory
    if ! [ -d $1 ]; then
        echo The paramater provides does not corresponds to a folder.
        return
    fi

    # Checks if there are a wp-config.php file inside the provided directory.
    wpconfigfile=$1/wp-config.php
    if [ -f $wpconfigfile ]; then
        echo The WordPress configuration file was not found. Did the path provided corresponds to a WordPress installation or does it is empty?
        return
    fi

    # If everything goes right, fetch the variables
    wpdbinfoapi_databasename=$(sed -n /define*.*DB_NAME/p $1 | cut -f4 -d\')
    wpdbinfoapi_databaseuser=$(sed -n /define*.*DB_USER/p $1 | cut -f4 -d\')
    wpdbinfoapi_databasepass=$(sed -n /define*.*DB_PASSWORD/p $1 | cut -f4 -d\')
    wpdbinfoapi_databasehost=$(sed -n /define*.*DB_HOST/p $1 | cut -f4 -d\')
}