#!/bin/bash

## This utility creates the followinf variables:
#  $wpdbinfoapi_iswordpresssite
#  $wpdbinfoapi_databasename
#  $wpdbinfoapi_databaseuser
#  $wpdbinfoapi_databasepass
#  $wpdbinfoapi_databasehost


##
# Utility version
#
wpdbinfoapi_version=4

##
# The main function,m that must be called by the outer script
#
do_wpdbinfoapi() {

    # Checks if the first parameter was provided
    if [ -z $1 ]; then
        echo You need provides the first paramater to be the wordpress base directory.
        return
    fi

    # Checks if the parameter provides corresponds to a directory
    if ! [ -d $1 ]; then
        echo The paramater provides does not corresponds to a folder.
        return
    fi

    # Checks if there are a wp-config.php file inside the provided directory.
    wpconfigfile=$1/wp-config.php
    if ! [ -f $wpconfigfile ]; then
        echo The WordPress configuration file was not found. Did the path provided corresponds to a WordPress installation or does it is empty?
		wpdbinfoapi_iswordpresssite=0
        return
    fi

    # If everything goes right, fetch the variables
	wpdbinfoapi_iswordpresssite=1
    wpdbinfoapi_databasename=$(sed -n /define*.*DB_NAME/p $wpconfigfile | cut -f4 -d\')
    wpdbinfoapi_databaseuser=$(sed -n /define*.*DB_USER/p $wpconfigfile | cut -f4 -d\')
    wpdbinfoapi_databasepass=$(sed -n /define*.*DB_PASSWORD/p $wpconfigfile | cut -f4 -d\')
    wpdbinfoapi_databasehost=$(sed -n /define*.*DB_HOST/p $wpconfigfile | cut -f4 -d\')
}
